//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatingApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calculator
    {
        public int id { get; set; }
        public Nullable<decimal> num1 { get; set; }
        public Nullable<decimal> num2 { get; set; }
        public string opt { get; set; }
        public Nullable<decimal> res { get; set; }
        public Nullable<System.DateTime> ondate { get; set; }
    }
}
